// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBscW_R9Ies3Bds3pvL0JLuQTQBLJXD3ts',
    appId: '1:1083938666263:web:d77f3252fa1689b820e952',
    messagingSenderId: '1083938666263',
    projectId: 'essential-hawk-413019',
    authDomain: 'essential-hawk-413019.firebaseapp.com',
    storageBucket: 'essential-hawk-413019.firebasestorage.app',
    measurementId: 'G-1FRYYB5MGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ZCp6ThtjG2d56oHItb-hi802n3-7Sww',
    appId: '1:1083938666263:android:49d3b6eb7573745320e952',
    messagingSenderId: '1083938666263',
    projectId: 'essential-hawk-413019',
    storageBucket: 'essential-hawk-413019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzHmJr4WjffMa5CMNgWKO5Tw2F3U0zddQ',
    appId: '1:1083938666263:ios:00d28e17b1fd7eeb20e952',
    messagingSenderId: '1083938666263',
    projectId: 'essential-hawk-413019',
    storageBucket: 'essential-hawk-413019.firebasestorage.app',
    iosBundleId: 'com.rzo.operations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzHmJr4WjffMa5CMNgWKO5Tw2F3U0zddQ',
    appId: '1:1083938666263:ios:b13f97d3c8214cad20e952',
    messagingSenderId: '1083938666263',
    projectId: 'essential-hawk-413019',
    storageBucket: 'essential-hawk-413019.firebasestorage.app',
    iosBundleId: 'com.example.saladafactory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBscW_R9Ies3Bds3pvL0JLuQTQBLJXD3ts',
    appId: '1:1083938666263:web:66e43f162474a8ee20e952',
    messagingSenderId: '1083938666263',
    projectId: 'essential-hawk-413019',
    authDomain: 'essential-hawk-413019.firebaseapp.com',
    storageBucket: 'essential-hawk-413019.firebasestorage.app',
    measurementId: 'G-S9EJ8KCRQ4',
  );
}
